alias cv='python3 -m venv .venv'
alias av='source .venv/bin/activate'
alias gs='git config credential.helper store'
alias gc='git clone'
alias l='ls -la'
alias ra='ranger'
alias vim='nvim'
alias lgit='lazygit'
alias proxy='source ~/.config/zsh/proxy.sh'
alias unproxy='unset ALL_PROXY'

